# Generated by Django 4.1.7 on 2023-04-27 19:34

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_banner_name_alter_banner_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='major',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='question',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='video',
            name='slug',
        ),
        migrations.AlterField(
            model_name='admission',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='title', unique=True),
        ),
        migrations.AlterField(
            model_name='admissiontype',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='type', unique=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='livestream',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='title', unique=True),
        ),
    ]
