# Generated by Django 4.1.7 on 2023-05-07 20:46

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0007_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('video', models.URLField(blank=True)),
                ('description', ckeditor.fields.RichTextField()),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
    ]
